// <auto-generated />
namespace CompuSPED.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class logDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(logDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202106152300267_logDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
